version: "3.8"

services:
  nodejs-api:
    image: nodejs-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-api-container_name
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - crud_backend_gestion_patient_default

  db:
    image: mysql
    container_name: db-container
    restart: always
    environment:
      MYSQL_DATABASE: gestion_patient
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - crud_backend_gestion_patient_default
    volumes:
      - crud_backend_gestion_patient_default:/data/db
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  crud_backend_gestion_patient_default:
    driver: bridge

volumes:
  crud_backend_gestion_patient_default:
